### PR TITLE
Title replace Typography.Title

### PR DESCRIPTION
**Pull request by Germiniku**

### CODE REVIEW

**Comment by zfben** [comment]
@Germiniku `Typography.Title` is too complex and not good for mobile, so I don't want it to be the default Title UI.

I prefer to use children for custom UI. for example:

```ts
function CustomTitle(props: { title: string }){
  return <Title title={ props.title }>
      <Typography.Title>{ props.title }</Typography.Title>
    </Title>
}
```

**Comment by Germiniku** [comment]
> Typography.Title

`Typography.Title` default render is `h1`,the complexity depends on the user's functional parameters.I'm going to use it as a custom UI.

**Comment by zfben** [comment]
@Germiniku I see you add CustomTitle to the package, I mean you can add it in your own projects.
For `@faasjs/ant-design`, it just needs to add `children` to props.

**Comment by Germiniku** [comment]
> @Germiniku I see you add CustomTitle to the package, I mean you can add it in your own projects. For `@faasjs/ant-design`, it just needs to add `children` to props.

ok,i close this pr

**Pull request closed without merging**
