### PR TITLE
[bug] added dev deps and fixed example file name(create-faas-app)

### PR DESCRIPTION
**Pull request by onichandame**
### Problems

1. When serving the example function locally using `faas server` command, an error is returned from the requests to the endpoint:
```text
{"error":{"message":"Not found: /git/scf/.func.ts or /git/scf//index.func.ts"}}
```
2. When running `jest` command in the newly created app with the auto-generated example, errors are reported stating that some babel plugins are missing.

### Cause

1. The root cause is that the server looks for `index.func.ts` by default. But the example function resides in `hello.func.ts`.
2. `@babel/preset-env` and `@babel/preset-typescript` are missing

### Fix

1. change the filename of the function to `index.func.ts`
2. add the missing dependencies to the example `package.json` as dev dependencies

### Off-Topic

When running `node_modules/.bin/eslint --ext .ts packages/create-faas-app/src/ --fix` to lint the source codes, the `{` brackets after `if` statement are removed. I am not sure if it is the intended behaviour so please can a maintainer double check the eslint rules?

### CODE REVIEW

**Comment by zfben** [comment]
目前 faasjs 基于 ts-jest 进行自动化测试，不再依赖 babel 了，所以这个脚本生成的 package.json 是错的，正确的可以参考 https://github.com/faasjs/faasjs/blob/master/examples/simple/package.json

**Comment by onichandame** [comment]
删除了babel，加入了ts-jest配置。local environment下已经测试通过

**Comment by zfben** [comment]
文件的代码风格好像被改了，麻烦还原一下

**Comment by onichandame** [comment]
已经复原。

在上一个commit中我用了`eslint --fix`，`create-faas-app`目录下的风格就被修改了，怀疑是`create-faas-app`目录下的风格与现有eslint rules有冲突

**Pull request merged**
